In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
os.chdir('C:/Users/hubst/Downloads')

In [2]:
acs = pd.read_csv('usa_00003.csv')
acs

,YEAR,SAMPLE,SERIAL,CBSERIAL,HHWT,CLUSTER,REGION,STATEFIP,COUNTYFIP,DENSITY,...,EMPSTAT,EMPSTATD,LABFORCE,OCC2010,IND1990,UHRSWORK,LOOKING,AVAILBLE,INCWAGE,POVERTY
0,2010,201001,1,69,96.0,2010000000011,32,1,0,86.9,...,3,30,1,9920,0,0,1,5,0,72
1,2010,201001,2,80,97.0,2010000000021,32,1,97,2305.8,...,1,10,2,1760,850,20,3,5,17000,172
2,2010,201001,2,80,97.0,2010000000021,32,1,97,2305.8,...,1,10,2,1020,850,20,3,5,13000,172
3,2010,201001,2,80,97.0,2010000000021,32,1,97,2305.8,...,0,0,0,9920,0,0,0,0,999999,172
4,2010,201001,3,140,90.0,2010000000031,32,1,0,316.7,...,3,30,1,9920,0,0,1,5,0,282
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31499763,2019,201901,1428035,2019001411842,29.0,2019014280351,41,56,0,43.1,...,1,10,2,5150,451,40,3,5,102000,501
31499764,2019,201901,1428035,2019001411842,29.0,2019014280351,41,56,0,43.1,...,2,20,2,9620,633,40,2,4,14000,501
31499765,2019,201901,1428036,2019001412021,51.0,2019014280361,41,56,0,34.2,...,3,30,1,9920,0,0,1,5,0,153
31499766,2019,201901,1428037,2019001412362,65.0,2019014280371,41,56,0,43.1,...,3,30,1,9920,0,0,1,5,0,386
31499767,2019,201901,1428037,2019001412362,65.0,2019014280371,41,56,0,43.1,...,3,30,1,9920,0,0,1,5,0,386

In [3]:
acs = acs.drop(columns = ['GQ','CITYPOP','LOOKING','AVAILBLE','HHWT','CBSERIAL','SAMPLE'])
acs = acs[acs['YEAR'] >= 2012]
acs = acs[acs['YEAR'] <= 2016]
acs = acs[acs['AGE'] >= 16]
acs = acs[acs['AGE'] <= 65]

In [4]:
mich = acs[acs['STATEFIP'] == 26]
wisc = acs[acs['STATEFIP'] == 55]

In [5]:
print(mich)
print(wisc)

          YEAR  SERIAL        CLUSTER  REGION  STATEFIP  COUNTYFIP  DENSITY  \
7593707   2012  615216  2012006152161      21        26        125   2899.0
7593708   2012  615217  2012006152171      21        26        115    476.4
7593709   2012  615217  2012006152171      21        26        115    476.4
7593714   2012  615219  2012006152191      21        26        145    684.7
7593715   2012  615219  2012006152191      21        26        145    684.7
...        ...     ...            ...     ...       ...        ...      ...
20239257  2016  669725  2016006697251      21        26          0   3701.5
20239258  2016  669726  2016006697261      21        26        163   6877.2
20239259  2016  669726  2016006697261      21        26        163   6877.2
20239260  2016  669726  2016006697261      21        26        163   6877.2
20239261  2016  669726  2016006697261      21        26        163   6877.2

          METRO  CITY  STRATA  ...  EDUC  EDUCD  EMPSTAT  EMPSTATD  LABFORCE  \
7593707       4     0  290726  ...     6     63        3        30         1
7593708       4     0  330026  ...     8     81        3        30         1
7593709       4     0  330026  ...    10    101        1        10         2
7593714       4     0  150026  ...     6     63        1        10         2
7593715       4     0  150026  ...     6     63        1        10         2
...         ...   ...     ...  ...   ...    ...      ...       ...       ...
20239257      2  2270  170326  ...     2     26        3        30         1
20239258      2  1750  320926  ...     6     63        1        10         2
20239259      2  1750  320926  ...     6     63        2        20         2
20239260      2  1750  320926  ...     6     63        2        20         2
20239261      2  1750  320926  ...     6     63        2        20         2

          OCC2010  IND1990  UHRSWORK  INCWAGE  POVERTY
7593707      9920        0         0        0        1
7593708      9920        0         0        0      296
7593709      1000      351        40    80000      296
7593714       310      641        47    27000      376
7593715      8965      731        48    30000      376
...           ...      ...       ...      ...      ...
20239257     9920        0         0        0        1
20239258     4720      682        20    15700      154
20239259     9600      272        42    18000      154
20239260     9920      992         0        0      154
20239261     9600      272        42    18000      154

[318060 rows x 28 columns]
          YEAR   SERIAL        CLUSTER  REGION  STATEFIP  COUNTYFIP  DENSITY  \
9222431   2012  1331415  2012013314151      21        55         79   6381.0
9222432   2012  1331416  2012013314161      21        55          0    168.5
9222433   2012  1331417  2012013314171      21        55          0     55.2
9222434   2012  1331417  2012013314171      21        55          0     55.2
9222437   2012  1331419  2012013314191      21        55          0    168.5
...        ...      ...            ...     ...       ...        ...      ...
21849828  2016  1377682  2016013776821      21        55         79   2140.7
21849829  2016  1377682  2016013776821      21        55         79   2140.7
21849830  2016  1377682  2016013776821      21        55         79   2140.7
21849831  2016  1377683  2016013776831      21        55        133   1617.5
21849832  2016  1377683  2016013776831      21        55        133   1617.5

          METRO  CITY   STRATA  ...  EDUC  EDUCD  EMPSTAT  EMPSTATD  LABFORCE  \
9222431       4     0  4010155  ...    10    101        1        10         2
9222432       0     0  5510255  ...     6     65        1        10         2
9222433       0     0  5510155  ...    10    101        1        10         2
9222434       0     0  5510155  ...     6     63        1        10         2
9222437       0     0  5510255  ...     8     81        1        10         2
...         ...   ...      ...  ...   ...    ...      ...       ...       ...
21849828      3     0  4030155  ...     7     71        1        10         2
21849829      3     0  4030155  ...     7     71        1        10         2
21849830      3     0  4030155  ...     6     65        1        10         2
21849831      4     0  7030155  ...    10    101        1        10         2
21849832      4     0  7030155  ...     6     63        1        10         2

          OCC2010  IND1990  UHRSWORK  INCWAGE  POVERTY
9222431      5240      581        12    10000      205
9222432      9130      410        70   331000      501
9222433       130      121        40    90000      501
9222434      4510      772        16     9000      501
9222437       430      931        40    45000      241
...           ...      ...       ...      ...      ...
21849828       30      893        20     3000      292
21849829     5400      812        20     6000      292
21849830     4050      641        15     4000      292
21849831     4600      761        15    11000       88
21849832     6440       60        40    34000      274

[188066 rows x 28 columns]

In [6]:
print(mich['AGE'].describe())
print(wisc['AGE'].describe())

count    318060.000000
mean         42.233560
std          14.802939
min          16.000000
25%          29.000000
50%          44.000000
75%          55.000000
max          65.000000
Name: AGE, dtype: float64
count    188066.000000
mean         42.629316
std          14.682713
min          16.000000
25%          30.000000
50%          45.000000
75%          55.000000
max          65.000000
Name: AGE, dtype: float64